---
all:
  hosts:
    k8s-node-01:
      ansible_host: 62.84.116.144
    k8s-node-02:
      ansible_host: 158.160.99.17
    k8s-node-03:
      ansible_host: 178.154.201.135
  vars:
    ansible_user: admin