apiVersion: v1
kind: Namespace
metadata:
  name: gitlab-runner
---
apiVersion: v1
kind: Secret
metadata:
  name: runner-secret
  namespace: gitlab-runner
  labels:
    author: nvk-r0dney
type: Opaque
stringData:
  runner-registration-token: ""
  runner-token: "glrt-yTZW64zdNF2zaXhcaNDR"
