imagePullPolicy: IfNotPresent
revisionHistoryLimit: 3
gitlabUrl: https://gitlab.ntlb.ru
terminationGracePeriodSeconds: 3600
concurrent: 2
checkInterval: 30
logLevel: info
logFormat: json
sessionServer:
  enabled: false
rbac:
  create: true
  rules:
    - resources: ["pods", "secrets", "configmaps"]
      verbs: ["get", "list", "watch", "create", "patch", "delete", "update"]
    - apiGroups: [""]
      resources: ["pods/exec", "pods/attach"]
      verbs: ["create", "patch", "delete"]
  clusterWideAccess: false
  podSecurityPolicy:
    enabled: false
    resourceNames:
      - gitlab-runner
metrics:
  enabled: true
  portName: metrics
  port: 9252
  serviceMonitor:
    enabled: false
service:
  enabled: false
runners:
  privileged: true
  config: |
    # log_level = "debug"
    [[runners]]
      output_limit = 10000
      [runners.kubernetes]
        image = "ubuntu:22.04"
        # helper_image = "if use custom helper"
  executor: kubernetes
  secret: runner-secret
securityContext:
  runAsUser: 100
  fsGroup: 65533

resources:
  limits:
    memory: 256Mi
    cpu: 200m
  requests:
    memory: 128Mi
    cpu: 100m
